export const LOGIN = {
  CHANGE: 'LOGIN_TEXT_CHNAGE',
  SUBMIT: 'LOGIN_SUBMIT_FORM',
  LOGIN: 'LOGIN_TO_ACCOUNT',
  SUCCESS: 'LOGIN_SCCUESS',
  FAILED: 'LOGIN_FAILED',
  OUT: 'LOGIN_OUT',
};

export const REGISTER = {
  CHANGE: 'REGISTER_TEXT_CHNAGE',
  SUBMIT: 'REGISTER_SUBMIT_FORM',
  CREATE: 'REGISTER_CREATE_ACCOUNT',
  SUCCESS: 'REGISTER_SCCUESS',
  FAILED: 'REGISTER_FAILEDS',
};

export const LOGOUT = {
  DONE: 'LOGGING_OUT',
  SUCCESS: 'LOGGIN_OUT_SUCCESS',
};

export const REACTGRAM = {
  ENABLEFORM: 'ENABLE_REACT_GRAM_FORM',
  DISABLEFORM: 'DISABLE_REACT_GRAM_FORM',
  CHANGEFORM: 'CHANGE_REACT_GRAM_FORM',
  EMPTYFIELDS: 'EMPTYFIELDS_REACT_GRAM_FORM',
  SHARE: 'SHARE_REACT_GRAM_STORY',
  SUCCESS: 'SUCCESS_REACT_GRAM',
  FAILED: 'FAILED_REACT_GRAM',
  LIKE: 'LIKE_REACTGRAM_STORY',
};
